spring:
  profiles:
    active: dev

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs


cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,DELETE,PUT,OPTIONS
  allowed-headers: Accept,Accept-Encoding,Accept-Language,Authorization,Connection,Content-Type,Host,Origin,Referer,User-Agent,X-Requested-With



  
  

    
